python __init__.py ../files/118.pdf.txt -p > ../files/118.p.out
python __init__.py ../files/118.pdf.txt -l > ../files/118.l.out
python __init__.py ../files/120.pdf.txt -l > ../files/120.l.out
python __init__.py ../files/120.pdf.txt -p > ../files/120.p.out
python __init__.py ../files/13.pdf.txt -l > ../files/13.l.out
python __init__.py ../files/13.pdf.txt -p > ../files/13.p.out
python __init__.py ../files/17.pdf.txt -l > ../files/17.l.out
python __init__.py ../files/17.pdf.txt -p > ../files/17.p.out
python __init__.py ../files/19.pdf.txt -l > ../files/19.l.out
python __init__.py ../files/19.pdf.txt -p > ../files/19.p.out
python __init__.py ../files/20.pdf.txt -l > ../files/20.l.out
python __init__.py ../files/20.pdf.txt -p > ../files/20.p.out
python __init__.py ../files/21.pdf.txt -l > ../files/21.l.out
python __init__.py ../files/21.pdf.txt -p > ../files/21.p.out
python __init__.py ../files/22.pdf.txt -l > ../files/22.l.out
python __init__.py ../files/22.pdf.txt -p > ../files/22.p.out
python __init__.py ../files/23.pdf.txt -l > ../files/23.l.out
python __init__.py ../files/23.pdf.txt -p > ../files/23.p.out
python __init__.py ../files/29.pdf.txt -l > ../files/29.l.out
python __init__.py ../files/29.pdf.txt -p > ../files/29.p.out
python __init__.py ../files/31.pdf.txt -l > ../files/31.l.out
python __init__.py ../files/31.pdf.txt -p > ../files/31.p.out
python __init__.py ../files/46.pdf.txt -l > ../files/46.l.out
python __init__.py ../files/46.pdf.txt -p > ../files/46.p.out
python __init__.py ../files/48.pdf.txt -l > ../files/48.l.out
python __init__.py ../files/48.pdf.txt -p > ../files/48.p.out
python __init__.py ../files/49.pdf.txt -l > ../files/49.l.out
python __init__.py ../files/49.pdf.txt -p > ../files/49.p.out
python __init__.py ../files/50.pdf.txt -l > ../files/50.l.out
python __init__.py ../files/50.pdf.txt -p > ../files/50.p.out
python __init__.py ../files/98.pdf.txt -l > ../files/98.l.out
python __init__.py ../files/98.pdf.txt -p > ../files/98.p.out
