
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABSTRACT CAPSTEXT GENERAL IEEE INDEX INTRO MONTH NUMBER REFERENCES VIRGULA YEARarticle : headerheader : code publication titleandauthor abstract keywordsheader : publication code titleandauthor abstract keywordscode : NUMBERpublication : IEEE text VIRGULA MONTH YEARabstract : ABSTRACT text INDEXkeywords : INDEX text INTROtitleandauthor : texttext : GENERAL'
    
_lr_action_items = {'INDEX':([10,16,17,19,24,],[-9,20,20,24,-6,]),'VIRGULA':([9,10,],[14,-9,]),'ABSTRACT':([10,11,12,13,],[-9,-8,15,15,]),'NUMBER':([0,2,23,],[3,3,-5,]),'GENERAL':([3,6,7,8,15,20,23,],[-4,10,10,10,10,10,-5,]),'INTRO':([10,25,],[-9,26,]),'YEAR':([18,],[23,]),'MONTH':([14,],[18,]),'IEEE':([0,1,3,],[6,6,-4,]),'$end':([4,5,21,22,26,],[-1,0,-2,-3,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'code':([0,2,],[1,8,]),'publication':([0,1,],[2,7,]),'text':([6,7,8,15,20,],[9,11,11,19,25,]),'abstract':([12,13,],[16,17,]),'titleandauthor':([7,8,],[12,13,]),'header':([0,],[4,]),'keywords':([16,17,],[21,22,]),'article':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> article","S'",1,None,None,None),
  ('article -> header','article',1,'p_article','parser.py',10),
  ('header -> code publication titleandauthor abstract keywords','header',5,'p_header_code','parser.py',15),
  ('header -> publication code titleandauthor abstract keywords','header',5,'p_header_pub','parser.py',19),
  ('code -> NUMBER','code',1,'p_code','parser.py',23),
  ('publication -> IEEE text VIRGULA MONTH YEAR','publication',5,'p_publication','parser.py',27),
  ('abstract -> ABSTRACT text INDEX','abstract',3,'p_abstract','parser.py',31),
  ('keywords -> INDEX text INTRO','keywords',3,'p_keywords','parser.py',35),
  ('titleandauthor -> text','titleandauthor',1,'p_titleandauthor','parser.py',47),
  ('text -> GENERAL','text',1,'p_text','parser.py',51),
]
